language: python
python:
  - 'pypy2.7'
  - 'pypy3.5'
  - '2.7'
  - '3.4'
  - '3.6'
  - 'nightly'
install:
  - pip install mock==2.0
  - pip install requests
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install .
script:
  - coverage run --source=messagebird -m unittest discover -s tests/
  - coverage report --fail-under=80
matrix:
  allow_failures:
  - python: 'nightly'
  - python: 'pypy2.7'
  - python: 'pypy3.5'
